version: '3.8'

services:
  scanner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sol_token_scanner
    volumes:
      - ./backend:/app/backend
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"